version: '3.8'

services:
  node-api:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge